export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const TRANSFER_MATIC_REQUEST = 'TRANSFER_MATIC_REQUEST'
export const TRANSFER_MATIC_SUCCESS = 'TRANSFER_MATIC_SUCCESS'

export const TRANSFER_RUBLE_REQUEST = 'TRANSFER_RUBLE_REQUEST'
export const TRANSFER_RUBLE_SUCCESS = 'TRANSFER_RUBLE_SUCCESS'

export const TRANSFER_NFT_REQUEST = 'TRANSFER_NFT_REQUEST'
export const TRANSFER_NFT_SUCCESS = 'TRANSFER_NFT_SUCCESS'

export const TRANSFER_STATUS_REQUEST = 'TRANSFER_STATUS_REQUEST'
export const TRANSFER_STATUS_SUCCESS = 'TRANSFER_STATUS_SUCCESS'

export const WALLET_BALANCE_REQUEST = 'WALLET_BALANCE_REQUEST'
export const WALLET_BALANCE_SUCCESS = 'WALLET_BALANCE_SUCCESS'

export const WALLET_NFT_BALANCE_REQUEST = 'WALLET_NFT_BALANCE_REQUEST'
export const WALLET_NFT_BALANCE_SUCCESS = 'WALLET_NFT_BALANCE_SUCCESS'

export const GENERATE_NFT_REQUEST = 'GENERATE_NFT_REQUEST'
export const GENERATE_NFT_SUCCESS = 'GENERATE_NFT_SUCCESS'

export const LIST_NFT_REQUEST = 'LIST_NFT_REQUEST'
export const LIST_NFT_SUCCESS = 'LIST_NFT_SUCCESS'

export const STATUS_NFT_REQUEST = 'STATUS_NFT_REQUEST'
export const STATUS_NFT_SUCCESS = 'STATUS_NFT_SUCCESS'

export const WALLET_HISTORY_REQUEST = 'WALLET_HISTORY_REQUEST'
export const WALLET_HISTORY_SUCCESS = 'WALLET_HISTORY_SUCCESS'